project_id = "rzxondizgsecijptvqtr"

[functions.send-discord-alert]
verify_jwt = false

[functions.course-ai-assistant]
verify_jwt = false

[functions.auto-send-discord-signals]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
